CREATE DATABASE IF NOT EXISTS `usersDB`;
CREATE DATABASE IF NOT EXISTS `productsDB`;
CREATE DATABASE IF NOT EXISTS `ordersDB`;
CREATE DATABASE IF NOT EXISTS `paymentDB`;
CREATE DATABASE IF NOT EXISTS `notificationDB`;
