server:
  port: 8091

spring.application.name: api-gateway



# add more paths, filters, predicates later.
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9000/realms/Hps-microservice"
  cloud:
    gateway:
      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**

eureka:
  instance.prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/



# okta:
#   oauth2:
#     client-id: 0oae558kdiXkZM1KI5d7
#     client-secret: KMynKhgxCkMUCpduORW5KYOwhUyrn0gRsZTBhEhsYjgqlwLn4BJe7jGVBgrhCqe9
#     issuer: https://dev-69493338.okta.com/oauth2/default
#     audience: api://default
#     scopes: openid, email, profile, offline_access
