spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/paymentDB
    username: root
    password: secret
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

eureka:
  instance.prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8083
application:
  config:
    product-url: http://localhost:8091/api/v1/products
    user-url: http://localhost:8091/api/v1/users
    order-url: http://localhost:9091/api/v1/orders
